version: "3.9"

services:
  comfyui:
    user: "1000:1000"
    image: a624669980/comfyui:latest-cu121
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    ports:
      - "8188:8188"
    volumes:
      - "/DATA/comfyui/models:/app/models"
      - "/DATA/comfyui/input:/app/input"
      - "/DATA/comfyui/temp:/app/output/temp"
      - "/DATA/comfyui/output:/app/output"
      

